<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */

$topContainer = $this->getChildHtml('topContainer');
?>
<div class="container header-container">
    <div class="header">
		<div class="row">
			<div class="col-md-6">
		        <?php if ($this->getIsHomePage()):?>
					<h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
				<?php else:?>
			        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
			    <?php endif?>
			</div>
			<div class="quick-access col-md-6">
				<?php echo $this->getChildHtml('topLinks') ?>
				<?php echo $this->getChildHtml('store_language') ?>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?></p>
			</div>
			<div class="topSearch col-md-6">
				<?php echo $this->getChildHtml('topSearch') ?>
			</div>
		</div>
		<?php if($topContainer): ?>
			<div class="row">
				<div class="col-md-12"><?php echo $topContainer; ?></div>
			</div>
		<?php endif; ?>
	    </div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
